### ISSUE TITLE
Connectivity fails when running in serial

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/parRSB#31]
**Describe the bug**
Sometime in the last month, something broke in parSB related to how the connectivity works for serial cases. When I run a case in serial, I get a negative Jacobian error for every element in the mesh, but this error disappears and the case runs as normal if I run in parallel. 

The reason I'm sure the error lies somewhere in parSB is because if you pre-generate the `.co2` file, there is no error. So something is wrong with the automatic `.co2` file generation for serial problems.

**To Reproduce**
I've attached a few input files that run with nekRS for you to replicate the problem. Download these files and run the following:

_This fails with negative Jacobian errors:_
```
nrsmpi pyramid 1 
```

_This works:_
```
nrsmpi pyramid 2
```

_This also works:_
```
gencon
nrsmpi pyramid 1
```

**Expected behavior**
Cases should be able to run in serial.

**Comment by aprilnovak** [comment]
Ok I don't know how to attach `.re2` files here, github doesn't support that. If you want to replicate with exactly the files I'm using, send me a message on the nekRS slack.

**Comment by thilinarmtb** [comment]
Thanks for reporting the issue @aprilnovak ! I got the .re2 file from @stgeke and I am looking into the issue.

**Comment by thilinarmtb** [comment]
I pushed a fix for this in #32. Now the `.re2` works in both serial and parallel.
Will merge it after testing on a few other meshes.

**Comment by thilinarmtb** [comment]
@stgeke : This can be closed now, right?
